name: ws_example
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  stream_channel: ^2.1.1

dev_dependencies:
  json_serializable: ^6.6.2
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.19.2
  build_runner: ^2.3.3
