name: ws_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  injectable: ^2.1.1
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  bloc: ^8.1.1
  web_socket_channel: ^2.4.0
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/
